### ISSUE TITLE
epic: project general issue

### ISSUE THREAD

**Issue by mckaygerhard** [darltrash/above#1]
i m glad to tke the issue number 1 to issued the project nature and features

* Its made in lua lang, so anybody can get into with minor knowledge of programming, Lua is an easy language to understand and is also not strict in syntax, making it digestible (not like Python).
* The code base is based on the Love framework for Lua, but with basic OpenGL calls capabilities, this project significantly modifies this.

**Above** was the original name for the project, and now it’s only the name of the engine, the game name is **MEADOWS**.

For coders those two are enought to describe it, but i hijacked the issue and posted so in such detail @darltrash  can correct anything on.. 

EOF

**Comment by Miqueas** [comment]
Lmao what

**Comment by darltrash** [comment]
@mckaygerhard honestly I dont expect people to mod my game, the engine is not made with the purpose of anyone making a game on it other than Meadows, it’s highly specific.

**Comment by darltrash** [comment]
@mckaygerhard Löve doesn’t support 3D, but it supports basic OpenGL calls that I can use to engineer a renderer

**Comment by darltrash** [comment]
@mckaygerhard Anyways, thank you for joining the project! It’s nice to see people actually care about this kind of stuff, honestly, thank you
